---
# tasks file for myrole
- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy template
  template:
    src: mytemplate.j2
    dest: index.html
  notify: restart nginx

- name: debug vars
  debug:
    var: appurl
